import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import {
  ArrowRight, BadgeCheck, BarChart3, CircleDollarSign,
  Clock3, Code2, Database, FlaskConical, Globe2, Landmark, Languages,
  MapPin, MessageSquareText, Network, Route, Satellite,
  ShieldCheck, Target,
} from "lucide-react";
import PublicExperienceNav from "@/components/shared/PublicExperienceNav";
import PitchFilm from "@/components/pitch/PitchFilm";

const FLOOD_IMAGE = "https://commons.wikimedia.org/wiki/Special:Redirect/file/Flood_apocalypse2.jpg?width=1800";
const GLOFAS_IMAGE = "https://commons.wikimedia.org/wiki/Special:Redirect/file/Disastrous_floods_affect_Nigeria.jpg?width=1800";

const funding = [
  ["Engineering + data infrastructure", "₦52.5m", "35%", "Harden the national decision loop, data lineage, API reliability and institutional controls."],
  ["Ground truth + relevant-environment validation", "₦37.5m", "25%", "Instrumented pilot sites, representative users, safety exercises and an independently reviewable evidence pack."],
  ["Institutional sales + implementation", "₦37.5m", "25%", "Convert pilots into procurement-ready agency, insurer, bank, agribusiness and infrastructure contracts."],
  ["Compliance, customer acquisition + IP", "₦15m", "10%", "Privacy, security, legal, onboarding and defensible product documentation."],
  ["Working capital", "₦7.5m", "5%", "Operating buffer tied to the 12-month evidence and commercialisation plan."],
];

const loop = [
  [MapPin, "Place or asset", "A home, farm, road, facility or portfolio is identified."],
  [Satellite, "Trusted signal", "Official warnings and traceable hazard evidence are brought together."],
  [Target, "Role-specific decision", "The right action is translated for the person who owns it."],
  [MessageSquareText, "Delivery + receipt", "Web, voice and message-ready workflows record whether it arrived."],
  [BadgeCheck, "Action + outcome", "The action taken and the result become evidence for the next decision."],
] as Array<[LucideIcon, string, string]>;

const capabilities = [
  [Globe2, "Public product", "Coordinate checks, saved places and role-based dashboards across the 36-state + FCT geography registry."],
  [ShieldCheck, "Action OS", "Warnings become owned tasks, deadlines, preparedness steps and auditable follow-through."],
  [Languages, "Last-mile access", "English, Nigerian Pidgin, Hausa, Yorùbá and Igbo interfaces with read-aloud support."],
  [Database, "Evidence layer", "Source, forecast, delivery, acknowledgement, action and outcome can be separated instead of blended into one score."],
  [Code2, "Commercial API", "Prepaid API credits, institutional workspaces, order verification and enterprise enquiries already exist in the product."],
  [BarChart3, "Founder command", "Collected cash, paid plans, checkout conversion, renewals and the institutional pipeline are visible at /admin."],
] as Array<[LucideIcon, string, string]>;

export default function PitchPage() {
  return (
    <main className="min-h-screen bg-[#f7f7f2] text-[#0d1f19] transition-colors dark:bg-[#07110e] dark:text-white">
      <PublicExperienceNav />

      <section id="purpose" className="relative overflow-hidden border-b border-black/8 px-4 pb-20 pt-28 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="pointer-events-none absolute -right-40 top-10 h-[34rem] w-[34rem] rounded-full bg-emerald-400/12 blur-3xl dark:bg-[#225d49]/28" />
        <div className="mx-auto grid min-h-[calc(100vh-7rem)] max-w-7xl gap-12 lg:grid-cols-[1.02fr_.98fr] lg:items-center">
          <div className="relative">
            <SlideLabel n="01" text="Purpose" />
            <h1 className="mt-5 max-w-4xl font-display text-5xl font-black leading-[.94] tracking-[-.055em] sm:text-6xl lg:text-[5.6rem]">NaijaClimaGuard turns flood warnings into assigned, delivered and verified action.</h1>
            <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 dark:text-white/65">It works beside agencies and global forecasting systems. The product begins where a forecast usually ends: <strong className="text-[#0d1f19] dark:text-white">who is exposed, what should happen now, who owns it, did the warning arrive, and did the action reduce loss?</strong></p>
            <div className="mt-8 flex flex-wrap gap-2">{["Agency briefing", "Investor pitch", "Competition final"].map((room) => <span key={room} className="rounded-full border border-black/12 bg-white/60 px-4 py-2 text-xs font-black dark:border-white/15 dark:bg-white/5">{room}</span>)}</div>
            <div className="mt-8 flex flex-wrap gap-3"><Link href="/my-area" className="inline-flex items-center gap-2 rounded-full bg-[#071713] px-6 py-3.5 font-black text-white dark:bg-[#d9ff57] dark:text-[#071713]">Open the product <ArrowRight className="h-4 w-4" /></Link><Link href="/investor-readiness" className="rounded-full border border-black/14 px-6 py-3.5 font-black dark:border-white/20">Inspect TRL 6 pathway</Link></div>
          </div>
          <div className="relative"><PitchFilm /></div>
        </div>
      </section>

      <section id="problem" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center">
          <div>
            <SlideLabel n="02" text="The problem" />
            <h2 className="mt-4 font-display text-4xl font-black leading-[1.01] tracking-[-.04em] sm:text-6xl">Nigeria does not only have a forecasting problem. It has a last-mile decision problem.</h2>
            <p className="mt-6 text-lg leading-8 text-slate-600 dark:text-white/62">Reports, maps and warnings can exist while the household, farmer, business operator or local responder still cannot answer four urgent questions:</p>
            <div className="mt-7 grid gap-3 sm:grid-cols-2">{["Am I actually exposed?", "What do I do next?", "Who is responsible?", "Can we prove the warning became action?"].map((item) => <div key={item} className="rounded-[22px] border border-black/8 bg-white p-5 font-black shadow-sm dark:border-white/8 dark:bg-white/[.045]">{item}</div>)}</div>
          </div>
          <figure className="overflow-hidden rounded-[2.25rem] bg-[#071713] shadow-[0_26px_80px_rgba(3,25,18,.18)]">
            <img src={FLOOD_IMAGE} alt="A flooded community in Rivers State during the 2022 Nigeria floods" className="h-[28rem] w-full object-cover" />
            <figcaption className="px-5 py-4 text-xs leading-5 text-white/62">A real 2022 flood scene in Rivers State. Photo: Hansel Ohioma, CC BY-SA 4.0 via <a className="font-bold text-[#d9ff57] underline" href="https://commons.wikimedia.org/wiki/File:Flood_apocalypse2.jpg" target="_blank" rel="noreferrer">Wikimedia Commons</a>.</figcaption>
          </figure>
        </div>
      </section>

      <section id="alternatives" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <SlideLabel n="03" text="What already exists" />
          <h2 className="mt-4 max-w-5xl font-display text-4xl font-black leading-tight sm:text-6xl">The ecosystem already has important tools. We are not pretending they do not exist.</h2>
          <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-600 dark:text-white/60">Official agencies have authority. Global systems have powerful hazard data. Sensor and dashboard providers improve monitoring. The open commercial space is the layer that connects those strengths to a local, owned and measurable decision.</p>
          <div className="mt-12 grid gap-3 lg:grid-cols-3"><Alternative icon={Landmark} title="Official agency systems" strength="Authority, public warnings, coordination and emergency response." role="NaijaClimaGuard preserves official authority and extends distribution, assignment and evidence." /><Alternative icon={Satellite} title="GloFAS / global platforms" strength="River forecasts, earth observation, hazard maps and large-scale monitoring." role="NaijaClimaGuard turns traceable hazard inputs into asset- and role-specific action workflows." /><Alternative icon={BarChart3} title="Dashboards / sensors" strength="Local monitoring, visualisation, telemetry and operational awareness." role="NaijaClimaGuard connects observation to delivery, acknowledgement, action and outcome." /></div>
          <p className="mt-8 border-l-4 border-emerald-600 pl-5 text-sm font-bold leading-7 dark:border-[#d9ff57] dark:text-white/68"><strong>Positioning:</strong> do not replace the national agencies or sell another flood map. Become the trusted decision, distribution and evidence layer that makes their intelligence more actionable.</p>
        </div>
      </section>

      <section id="product" className="scroll-mt-20 border-b border-black/8 bg-white/55 px-4 py-24 dark:border-white/10 dark:bg-white/[.018] sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <SlideLabel n="04" text="The product in 30 seconds" />
          <h2 className="mt-4 max-w-5xl font-display text-4xl font-black leading-tight sm:text-6xl">The forecast is an input. The closed decision loop is the product.</h2>
          <div className="mt-12 grid gap-3 lg:grid-cols-5">{loop.map(([Icon, title, body], index) => <article key={title} className="relative rounded-[26px] border border-black/8 bg-[#f7f7f2] p-6 dark:border-white/8 dark:bg-[#0d211a]"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-emerald-700 dark:text-[#d9ff57]" /><span className="font-mono text-[10px] font-black text-slate-400">0{index + 1}</span></div><h3 className="mt-8 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-white/52">{body}</p></article>)}</div>
          <div className="mt-10 grid gap-4 sm:grid-cols-3"><ProductLink href="/my-area" title="Citizen experience" text="Check a place and save what matters." /><ProductLink href="/action-center" title="Action OS" text="See who should do what and when." /><ProductLink href="/evidence" title="Evidence history" text="Inspect what was known and recorded." /></div>
        </div>
      </section>

      <section id="innovation" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]">
          <div><SlideLabel n="05" text="Why this is different" /><h2 className="mt-4 font-display text-4xl font-black leading-tight sm:text-6xl">Four defensible layers, not one AI feature.</h2><p className="mt-6 text-lg leading-8 text-slate-600 dark:text-white/58">The moat is the growing network of decision rules, delivery evidence, action records and verified outcomes—not a single model that another team can copy.</p></div>
          <div className="grid gap-3 sm:grid-cols-2"><Innovation icon={Target} title="Decision intelligence" text="The same hazard becomes a different action for a household, farm, agency, lender or infrastructure operator." /><Innovation icon={Languages} title="Last-mile usability" text="Five Nigerian language experiences and voice support make the warning usable, not merely available." /><Innovation icon={Network} title="Action evidence graph" text="Source, place, owner, delivery, acknowledgement, action and outcome form a traceable record." /><Innovation icon={CircleDollarSign} title="Economic verification" text="Exposure, intervention cost and observed result create a route to defensible benefit-cost evidence." /></div>
        </div>
      </section>

      <section id="working-now" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl"><SlideLabel n="06" text="What works today" /><h2 className="mt-4 max-w-5xl font-display text-4xl font-black leading-tight sm:text-6xl">A working national product experience—not a nationally validated prediction claim.</h2><div className="mt-10 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{capabilities.map(([Icon,title,text]) => <Innovation key={title} icon={Icon} title={title} text={text} />)}</div><div className="mt-8 rounded-[26px] bg-[#071713] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-[#d9ff57]">The honest distinction</p><p className="mt-3 max-w-4xl text-lg font-bold leading-8">All 36 states + FCT are represented in the product geography. Riverine Watch v1 evidence currently covers only its stated Lokoja and Makurdi evaluation. Product availability is not the same thing as nationwide model accuracy.</p></div></div>
      </section>

      <section id="evidence" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.76fr_1.24fr]"><div><SlideLabel n="07" text="Evidence" /><h2 className="mt-4 font-display text-4xl font-black leading-tight sm:text-6xl">The evidence is narrow, frozen and inspectable.</h2><p className="mt-6 text-lg leading-8 text-slate-600 dark:text-white/58">Riverine Watch v1 is a 14-day riverine shadow candidate tested retrospectively for Lokoja and Makurdi. The 80% headline is only one part of the result.</p><Link href="/model-evidence" className="mt-7 inline-flex items-center gap-2 font-black text-emerald-700 dark:text-[#d9ff57]">Open the full evidence pack <ArrowRight className="h-4 w-4" /></Link></div><div className="grid overflow-hidden rounded-[30px] border border-black/8 bg-white dark:border-white/10 dark:bg-white/[.035] sm:grid-cols-2">{[["4 / 5","Eligible historical flood-onset events detected"],["26.7%","Alert-episode precision"],["1.83","False alert episodes per location-year"],["0.176 / 0.837","PR-AUC / ROC-AUC"]].map(([value,label],index) => <div key={label} className={`p-7 ${index%2 ? "sm:border-l sm:border-black/8 sm:dark:border-white/8" : ""} ${index>1 ? "border-t border-black/8 dark:border-white/8" : index ? "border-t border-black/8 dark:border-white/8 sm:border-t-0" : ""}`}><p className="font-display text-4xl font-black text-emerald-700 dark:text-[#d9ff57]">{value}</p><p className="mt-3 text-sm font-bold text-slate-600 dark:text-white/62">{label}</p></div>)}</div></div>
      </section>

      <section id="glofas" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><SlideLabel n="08" text="What we are doing with GloFAS now" /><h2 className="mt-4 font-display text-4xl font-black leading-tight sm:text-6xl">Preserve. Replay. Shadow. Validate. Then promote.</h2><p className="mt-6 text-lg leading-8 text-slate-600 dark:text-white/60"><strong className="text-[#0d1f19] dark:text-white">GloFAS provides modelled river-discharge forecasts; it is not a local physical river gauge.</strong> It is not currently controlling the public national risk score. We are building the evidence required before it can responsibly influence public action.</p></div><figure className="overflow-hidden rounded-[2rem] bg-[#071713]"><img src={GLOFAS_IMAGE} alt="Copernicus Sentinel satellite view of flooding in Kogi State, Nigeria" className="h-80 w-full object-cover" /><figcaption className="px-5 py-4 text-xs leading-5 text-white/60">Satellite view of 2022 flooding near Gerinya, Kogi. Contains modified Copernicus Sentinel data 2022 via <a href="https://commons.wikimedia.org/wiki/File:Disastrous_floods_affect_Nigeria.jpg" target="_blank" rel="noreferrer" className="font-bold text-[#d9ff57] underline">Wikimedia Commons</a>.</figcaption></figure></div>
          <div className="mt-12 grid gap-3 lg:grid-cols-3"><Roadmap icon={Database} label="Completed" title="Reproducible frozen replay" body="A preserved NASA IMERG + operational GloFAS bundle can be replayed deterministically for the stated two-location evidence pack." /><Roadmap icon={Clock3} label="Running now" title="Prospective shadow archive" body="Daily model inputs are kept beside the public engine so freshness, source changes, missed events and false-alert burden can be examined over time." /><Roadmap icon={FlaskConical} label="Promotion gate" title="Relevant-environment proof" body="Field ground truth, representative users, official-source precedence, safety exercises and independent review must pass before public promotion." /></div>
          <div className="mt-6 rounded-[24px] border border-amber-400/30 bg-amber-50 p-5 text-sm font-bold leading-7 text-amber-950 dark:bg-amber-300/8 dark:text-amber-100">This workstream is visible because waiting for evidence is part of responsible product development—not a missing feature to hide. The current public system remains useful while the stronger riverine model is tested beside it.</div>
        </div>
      </section>

      <section id="why-now" className="scroll-mt-20 border-b border-black/8 bg-[#d9ff57] px-4 py-24 text-[#071713] sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.22em]">09 · Why now</p><h2 className="mt-4 max-w-5xl font-display text-5xl font-black leading-[.98] tracking-tight sm:text-7xl">The data exists. The phones exist. The missing infrastructure is the action network between warning and outcome.</h2><div className="mt-12 grid gap-4 md:grid-cols-3"><PitchMetric icon={Satellite} title="Better open intelligence" text="Earth observation and global forecasting inputs can now be preserved and combined with official warning context." /><PitchMetric icon={MessageSquareText} title="Reach is possible" text="Web, messaging and voice make role-specific guidance more accessible than a specialist dashboard alone." /><PitchMetric icon={CircleDollarSign} title="Value must be proved" text="Institutions increasingly need evidence of who was reached, what was done and what value an intervention protected." /></div><p className="mt-9 max-w-3xl text-sm font-bold leading-7 text-[#163129]/72">The historical World Bank estimate of $6.68bn median direct damage from Nigeria&apos;s 2022 floods is a market-exposure reference—not NaijaClimaGuard revenue and not a claimed saving.</p></div>
      </section>

      <section id="competition" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl"><SlideLabel n="10" text="Competition and category" /><h2 className="mt-4 max-w-5xl font-display text-4xl font-black leading-tight sm:text-6xl">Win by owning the closed decision loop—not by claiming to forecast better than every source.</h2><div className="mt-10 overflow-x-auto rounded-[28px] border border-black/8 bg-white dark:border-white/8 dark:bg-white/[.035]"><table className="w-full min-w-[820px] text-left text-sm"><thead><tr className="border-b border-black/8 bg-[#eef1e9] dark:border-white/8 dark:bg-white/[.05]"><th className="p-5 font-black">Category</th><th className="p-5 font-black">Core strength</th><th className="p-5 font-black">NaijaClimaGuard relationship</th><th className="p-5 font-black">Strategic edge we build</th></tr></thead><tbody className="divide-y divide-black/7 dark:divide-white/7"><MatrixRow category="Official agency systems" strength="Authority, warnings and coordination" relationship="Complement and preserve authority" edge="Delivery, ownership and action evidence" /><MatrixRow category="Global forecast platforms" strength="Hazard modelling and maps" relationship="Use traceable inputs where authorised" edge="Local asset- and role-specific decisions" /><MatrixRow category="Sensors and dashboards" strength="Observation and visualisation" relationship="Integrate useful local signals" edge="Receipt, action and outcome ledger" /><MatrixRow category="NaijaClimaGuard" strength="Decision, distribution and evidence OS" relationship="Runs beside all three" edge="Compounding Nigerian action-and-outcome network" highlight /></tbody></table></div></div>
      </section>

      <section id="business" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><SlideLabel n="11" text="Business model" /><h2 className="mt-4 font-display text-4xl font-black leading-tight sm:text-6xl">Keep essential checks useful. Charge for reach, portfolios, workflows and proof.</h2><p className="mt-6 text-lg leading-8 text-slate-600 dark:text-white/58">The person receiving safety guidance does not always have to be the person paying. Families, businesses and institutions buy deeper capability and sponsored protection.</p><Link href="/commercial" className="mt-7 inline-flex items-center gap-2 font-black text-emerald-700 dark:text-[#d9ff57]">Open live commercial products <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2"><Offer title="Citizen access" price="Free core checks" body="Area checks, public context and basic safety actions keep the public layer useful." /><Offer title="Family Plus" price="₦12,000 / year" body="More protected places, family workflows, priority delivery options and richer history." /><Offer title="Business Starter" price="₦120,000 / year" body="Portfolio monitoring, five-seat workspace, evidence and operational exports." /><Offer title="API" price="₦50k–₦350k prepaid" body="10,000 or 100,000 credits for teams integrating the intelligence layer." /><Offer title="Institutional command" price="Annual licence + implementation" body="Command workflows, integrations, training, sponsored reach, service levels and evidence packs." /><Offer title="White-label network" price="Setup + annual licence + usage" body="Banks, insurers, telcos and platforms distribute the protection layer inside existing relationships." /></div></div>
      </section>

      <section id="go-to-market" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl"><SlideLabel n="12" text="Proof to procurement" /><h2 className="mt-4 max-w-5xl font-display text-4xl font-black leading-tight sm:text-6xl">Do not manufacture traction. Build the shortest credible path to repeatable contracts.</h2><div className="mt-12 grid gap-3 lg:grid-cols-4"><Stage n="01" title="Partner pilot" text="Agree a specific location, users, decision and official-source protocol." /><Stage n="02" title="Relevant-environment proof" text="Run shadow operations, ground truth, delivery and safety exercises." /><Stage n="03" title="Case evidence" text="Measure reach, action completion, operational value and limitations." /><Stage n="04" title="Procurement" text="Convert the verified workflow into a licence, API, portfolio or sponsored-reach contract." /></div><p className="mt-7 text-sm font-bold text-slate-500 dark:text-white/48">Current status: product and commercial rails exist; paid traction and field-validated outcomes are not presented as achieved until the underlying records exist.</p></div>
      </section>

      <section id="team" className="scroll-mt-20 border-b border-black/8 px-4 py-24 dark:border-white/10 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><SlideLabel n="13" text="Founder and build advantage" /><div className="mt-7 flex h-28 w-28 items-center justify-center rounded-[2rem] bg-[#071713] font-display text-4xl font-black text-[#d9ff57]">MMB</div></div><div><h2 className="font-display text-4xl font-black leading-tight sm:text-6xl">A Nigerian product built close to the problem—and designed to earn institutional trust.</h2><p className="mt-6 text-lg leading-8 text-slate-600 dark:text-white/60"><strong className="text-[#0d1f19] dark:text-white">Muhammad Mustapha Bello, Founder.</strong> Computer-science, machine-learning, product and technology-education experience are being combined into one evidence-led operating system for Nigerian climate action.</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><MiniProof value="MSc" label="Computer Science" /><MiniProof value="4+ years" label="Technology ecosystem experience" /><MiniProof value="500+" label="Learners taught" /></div><p className="mt-6 text-sm leading-7 text-slate-500 dark:text-white/48">Next critical hires and advisors: hydrology, field operations, institutional sales, data protection and independent safety/evidence review.</p></div></div>
      </section>

      <section id="ask" className="scroll-mt-20 px-4 py-28 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><SlideLabel n="14" text="The ask" /><h2 className="mt-4 font-display text-5xl font-black leading-[.98] tracking-tight sm:text-7xl">₦150 million for 12 months of field proof and repeatable adoption.</h2><p className="mt-7 text-lg leading-8 text-slate-600 dark:text-white/60">Approximately US$95k at the planning exchange rate. The naira amount is the governing ask.</p></div><div className="overflow-hidden rounded-[28px] border border-black/8 bg-white dark:border-white/10 dark:bg-white/[.035]">{funding.map(([label,value,percent,note],index) => <div key={label} className={`grid gap-2 p-5 sm:grid-cols-[1fr_auto_auto] sm:items-start sm:gap-5 ${index ? "border-t border-black/8 dark:border-white/8" : ""}`}><div><p className="font-black">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-white/45">{note}</p></div><strong className="font-mono text-sm text-emerald-700 dark:text-[#d9ff57]">{value}</strong><span className="text-right text-xs font-black text-slate-400">{percent}</span></div>)}</div></div><div className="mt-12 grid gap-4 md:grid-cols-3"><Milestone icon={Clock3} title="Signed field proof" body="A relevant-environment demonstration with representative users, ground truth and safety exercises." /><Milestone icon={Route} title="Operational GloFAS gate" body="Prospective source archive, field comparison and controlled promotion decision." /><Milestone icon={Network} title="Repeatable procurement" body="Agency and institutional pilots converted into defensible case evidence and a contract path." /></div><div className="mt-12 rounded-[34px] bg-[#071713] p-7 text-white sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-[#d9ff57]">The company we are building</p><p className="mt-4 max-w-5xl font-display text-3xl font-black leading-tight sm:text-5xl">The default action-and-evidence network institutions use to protect people, assets and economic activity before Nigerian flood risk becomes loss.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/investor-readiness" className="rounded-full bg-[#d9ff57] px-6 py-3.5 text-center font-black text-[#071713]">Inspect Investor + TRL 6 proof</Link><Link href="/institutional-pilot" className="rounded-full border border-white/20 px-6 py-3.5 text-center font-black text-white">Design a pilot</Link><Link href="/api-docs" className="rounded-full border border-white/20 px-6 py-3.5 text-center font-black text-white">Explore the API</Link></div></div></div>
      </section>
    </main>
  );
}

function SlideLabel({ n, text }: { n: string; text: string }) { return <p className="text-xs font-black uppercase tracking-[.22em] text-emerald-700 dark:text-[#d9ff57]">{n} · {text}</p>; }
function Alternative({ icon: Icon, title, strength, role }: { icon: LucideIcon; title: string; strength: string; role: string }) { return <article className="rounded-[28px] border border-black/8 bg-white p-7 dark:border-white/8 dark:bg-white/[.04]"><Icon className="h-7 w-7 text-emerald-700 dark:text-[#d9ff57]" /><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-white/55"><strong className="text-[#0d1f19] dark:text-white">Core strength:</strong> {strength}</p><p className="mt-4 border-t border-black/7 pt-4 text-sm leading-6 text-slate-600 dark:border-white/8 dark:text-white/55"><strong className="text-[#0d1f19] dark:text-white">Our role:</strong> {role}</p></article>; }
function ProductLink({ href, title, text }: { href: string; title: string; text: string }) { return <Link href={href} className="group rounded-[25px] bg-[#071713] p-6 text-white"><div className="flex items-center justify-between"><span className="text-lg font-black">{title}</span><ArrowRight className="h-4 w-4 text-[#d9ff57] transition group-hover:translate-x-1" /></div><p className="mt-3 text-sm text-white/55">{text}</p></Link>; }
function Innovation({ icon: Icon, title, text }: { icon: LucideIcon; title: string; text: string }) { return <article className="rounded-[26px] border border-black/8 bg-white p-6 dark:border-white/8 dark:bg-white/[.04]"><Icon className="h-6 w-6 text-emerald-700 dark:text-[#d9ff57]" /><h3 className="mt-7 text-2xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-white/54">{text}</p></article>; }
function Roadmap({ icon: Icon, label, title, body }: { icon: LucideIcon; label: string; title: string; body: string }) { return <article className="rounded-[28px] border border-black/8 bg-white p-7 dark:border-white/8 dark:bg-white/[.04]"><Icon className="h-6 w-6 text-emerald-700 dark:text-[#d9ff57]" /><p className="mt-8 text-xs font-black uppercase tracking-[.16em] text-emerald-700 dark:text-[#d9ff57]">{label}</p><h3 className="mt-3 text-2xl font-black">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-white/55">{body}</p></article>; }
function PitchMetric({ icon: Icon, title, text }: { icon: LucideIcon; title: string; text: string }) { return <div className="border-t-2 border-[#071713] py-6"><Icon className="h-7 w-7" /><p className="mt-8 text-2xl font-black">{title}</p><p className="mt-2 text-sm leading-6 text-[#071713]/65">{text}</p></div>; }
function MatrixRow({ category, strength, relationship, edge, highlight = false }: { category: string; strength: string; relationship: string; edge: string; highlight?: boolean }) { return <tr className={highlight ? "bg-[#d9ff57]/55 text-[#071713] dark:bg-[#d9ff57]" : ""}><td className="p-5 font-black">{category}</td><td className={`p-5 ${highlight ? "text-[#071713]/70" : "text-slate-600 dark:text-white/55"}`}>{strength}</td><td className={`p-5 ${highlight ? "text-[#071713]/70" : "text-slate-600 dark:text-white/55"}`}>{relationship}</td><td className="p-5 font-bold">{edge}</td></tr>; }
function Offer({ title, price, body }: { title: string; price: string; body: string }) { return <article className="rounded-[26px] border border-black/8 bg-white p-6 dark:border-white/8 dark:bg-white/[.04]"><p className="text-xs font-black uppercase tracking-[.15em] text-emerald-700 dark:text-[#d9ff57]">{title}</p><p className="mt-3 text-2xl font-black">{price}</p><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-white/52">{body}</p></article>; }
function Stage({ n, title, text }: { n: string; title: string; text: string }) { return <article className="border-t-2 border-emerald-700 py-6 dark:border-[#d9ff57]"><p className="font-mono text-xs font-black text-emerald-700 dark:text-[#d9ff57]">{n}</p><h3 className="mt-6 text-2xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-white/52">{text}</p></article>; }
function MiniProof({ value, label }: { value: string; label: string }) { return <div className="rounded-[24px] border border-black/8 bg-white p-5 dark:border-white/8 dark:bg-white/[.04]"><p className="text-3xl font-black text-emerald-700 dark:text-[#d9ff57]">{value}</p><p className="mt-2 text-xs font-bold text-slate-500 dark:text-white/45">{label}</p></div>; }
function Milestone({ icon: Icon, title, body }: { icon: LucideIcon; title: string; body: string }) { return <div className="border-t border-black/15 py-6 dark:border-white/15"><Icon className="h-5 w-5 text-emerald-700 dark:text-[#d9ff57]" /><h3 className="mt-6 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-white/52">{body}</p></div>; }
