import type { AppLocale } from "./config";

type Row = [pcm: string, ha: string, yo: string, ig: string];

/** Exact translations for safety/action sentences on Action OS, drills and the offline pack. */
const ROWS: Record<string, Row> = {
  "Important documents and medicines are together in one grab-ready place.": ["Important document and medicine dey together for one place wey you fit carry quick.", "Takardu masu muhimmanci da magunguna suna wuri daya da za a iya dauka da sauri.", "Àwọn ìwé pàtàkì àti oogun wà papọ̀ níbi kan tí a lè gbé kíákíá.", "Akwụkwọ dị mkpa na ọgwụ nọkọrọ n'otu ebe a pụrụ iburu ngwa ngwa."],
  "Everyone in the household knows who to call and where to meet if separated.": ["Everybody for house know who to call and where una go meet if una separate.", "Kowa a gida ya san wanda zai kira da inda za a hadu idan an rabu.", "Gbogbo ènìyàn nílé mọ ẹni tí wọn máa pè àti ibi tí wọn máa pàdé tí wọ́n bá yapa.", "Onye ọ bụla n'ụlọ maara onye ọ ga-akpọ na ebe a ga-ezukọ ma ọ bụrụ na ekewaa."],
  "Phones/power banks are charged and emergency contacts are written down offline.": ["Phone/power bank charge and emergency contact dey written down offline.", "An caji waya/power bank kuma an rubuta lambobin gaggawa a wajen intanet.", "Fóònù/power bank ti gba agbára, a sì ti kọ àwọn nọ́mbà pajawiri sílẹ̀ láìsí ayélujára.", "E chajiela ekwentị/power bank, e dekwara kọntaktị mberede n'ebe offline."],
  "Valuables and electrical items can be moved above likely water level quickly.": ["Valuable and electrical things fit move go higher place quick.", "Ana iya daga kayan daraja da na lantarki sama da inda ruwa zai iya kaiwa cikin sauri.", "A lè gbe ohun iyebíye àti ohun èlò iná sókè ju ibi tí omi lè dé lọ kíákíá.", "A pụrụ ibugharị ihe bara uru na ngwa eletrik elu karịa ebe mmiri nwere ike iru ngwa ngwa."],
  "Check any official warning shown above before the model score.": ["Check any official warning first before model score.", "Duba duk gargadin hukuma da farko kafin makin model.", "Ṣàyẹ̀wò ìkìlọ̀ ìjọba kọ́kọ́ kí o tó wo iye model.", "Lelee ịdọ aka ná ntị gọọmenti mbụ tupu akara model."],
  "Tell the people in your household what the current situation is.": ["Tell everybody for house wetin dey happen now.", "Faɗa wa mutanen gida halin da ake ciki yanzu.", "Sọ fún àwọn ènìyàn ilé ohun tó ń ṣẹlẹ̀ báyìí.", "Gwa ndị nọ n'ụlọ ihe ọnọdụ dị ugbu a."],
  "Keep children and vulnerable people away from drains, channels and rising water.": ["Keep children and people wey need extra help far from drain, channel and rising water.", "Kiyaye yara da masu bukatar taimako daga magudanan ruwa da ruwa mai tashi.", "Jẹ́ kí ọmọde àti àwọn tó nílò ìrànlọ́wọ́ jìnnà sí kòtò, ikanni àti omi tó ń gòkè.", "Debe ụmụaka na ndị chọrọ enyemaka pụọ na ọwa mmiri na mmiri na-arị elu."],
  "Charge phones and power banks.": ["Charge phone and power bank.", "Caji waya da power bank.", "Gba fóònù àti power bank lágbára.", "Chajie ekwentị na power bank."],
  "Move documents, medicines and important items higher.": ["Carry document, medicine and important things go higher place.", "Daga takardu, magunguna da muhimman kaya zuwa sama.", "Gbe ìwé, oogun àti ohun pàtàkì sókè.", "Bugharịa akwụkwọ, ọgwụ na ihe dị mkpa elu."],
  "Decide where you would go if an authority tells you to relocate; do not invent a route from this app.": ["Know where you go move to if authority tell you; no use this app invent road.", "Ka san inda za ka je idan hukuma ta ce ka matsa; kada ka kirkiri hanya daga manhajar nan.", "Mọ ibi tí iwọ yóò lọ tí aláṣẹ bá ní kí o kúrò; má ṣe dá ọ̀nà tuntun sílẹ̀ láti inú app yìí.", "Mara ebe ị ga-aga ma ọ bụrụ na ọchịchị agwa gị ka ị kwaga; emepụtala ụzọ site na app a."],
  "Follow official evacuation/relocation instructions immediately.": ["Follow official evacuation or relocation instruction immediately.", "Bi umarnin ficewa ko matsawa na hukuma nan take.", "Tẹ̀lé ìlànà ìkúrò tàbí ìṣípo ìjọba lẹ́sẹ̀kẹsẹ̀.", "Soro ntuziaka gọọmenti gbasara ịpụ ma ọ bụ ịkwaga ozugbo."],
  "Do not drive or walk through floodwater.": ["No drive or waka enter floodwater.", "Kada ka tuki ko tafiya cikin ruwan ambaliya.", "Má wakọ̀ tàbí rìn nínú omi ìkún.", "Ekwọla ụgbọala ma ọ bụ jee ije n'ime mmiri idei."],
  "Report visible flooding so the community/agency layer has ground evidence.": ["Report flood wey you see make community/agency get ground evidence.", "Bayar da rahoton ambaliyar da ka gani domin al'umma/hukuma su samu shaidar fili.", "Jábọ̀ ìkún omi tí o rí kí àwùjọ/aláṣẹ lè ní ẹ̀rí lórí ilẹ̀.", "Kọwaa idei mmiri ị hụrụ ka obodo/ụlọ ọrụ nwee ihe akaebe n'ebe ahụ."],

  "Livestock movement and safe holding arrangements are known in advance.": ["Plan for livestock movement and safe holding don ready before time.", "An san tsarin motsa dabbobi da wurin ajiyarsu lafiya tun da wuri.", "A ti mọ ètò gbigbe ẹran-ọ̀sìn àti ibi ààbò wọn ṣáájú.", "A maara atụmatụ ibugharị anụ ụlọ na ebe nchekwa ha tupu oge eruo."],
  "Seed, fertiliser, chemicals, feed and records can be moved above likely water level.": ["Seed, fertilizer, chemical, feed and record fit move go higher place.", "Ana iya daga iri, taki, sinadarai, abincin dabbobi da bayanai sama da inda ruwa zai kai.", "A lè gbe irúgbìn, ajílẹ̀, kẹ́míkà, oúnjẹ ẹran àti àkọsílẹ̀ sókè ju ibi omi lọ.", "A pụrụ ibugharị mkpụrụ, fatịlaịza, kemịkal, nri anụ na ndekọ elu karịa ebe mmiri ga-eru."],
  "Farm workers know the stop-work and communication plan.": ["Farm workers know when to stop work and how to communicate.", "Ma'aikatan gona sun san lokacin dakatar da aiki da tsarin sadarwa.", "Àwọn òṣìṣẹ́ oko mọ ìgbà tí wọn máa dá iṣẹ́ dúró àti ètò ìbánisọ̀rọ̀.", "Ndị ọrụ ubi maara mgbe a ga-akwụsị ọrụ na usoro nkwukọrịta."],
  "Photos/inventory of major farm assets are stored for later evidence and claims.": ["Photo/inventory of important farm assets dey stored for evidence and claim later.", "An adana hotuna/jadawalin muhimman kadarorin gona don shaida da da'awa daga baya.", "A ti pa fọ́tò/àkọsílẹ̀ ohun-ini oko pàtàkì mọ́ fún ẹ̀rí àti ẹ̀tọ́ ní ọjọ́ iwájú.", "E chekwara foto/ndepụta akụ ubi dị mkpa maka ihe akaebe na nkwupụta n'ọdịnihu."],
  "Check the official-warning overlay and rainfall risk together.": ["Check official warning and rainfall risk together.", "Duba gargadin hukuma da hadarin ruwan sama tare.", "Ṣàyẹ̀wò ìkìlọ̀ ìjọba àti ewu òjò papọ̀.", "Lelee ịdọ aka ná ntị gọọmenti na ihe ize ndụ mmiri ozuzo ọnụ."],
  "Identify animals, stored inputs and equipment that would be hardest to replace.": ["Know the animals, stored inputs and equipment wey hard to replace.", "Gano dabbobi, kayan ajiya da na'urorin da suka fi wahalar maye gurbi.", "Mọ ẹran, ohun èlò tí a fipamọ́ àti ẹrọ tí yóò nira jù láti rọ́pò.", "Chọpụta anụ, ihe echekwara na akụrụngwa ga-esiri ike dochie."],
  "Tell workers not to cross flooded fields, culverts or roads.": ["Tell workers make dem no cross flooded farm, culvert or road.", "Faɗa wa ma'aikata kada su ketare gonaki, magudanan hanya ko titunan da ruwa ya rufe.", "Sọ fún òṣìṣẹ́ pé kí wọn má kọjá oko, culvert tàbí ọ̀nà tí omi bo.", "Gwa ndị ọrụ ka ha ghara ịgafe ubi, culvert ma ọ bụ ụzọ mmiri jupụtara."],
  "Move portable inputs and records to higher/drier storage.": ["Move things and record wey you fit carry go higher/drier store.", "Motsa kayan da za a iya dauka da bayanai zuwa ajiya mafi tsayi/k bushe.", "Gbe ohun èlò àti àkọsílẹ̀ tí a lè rú lọ sí ibi tó ga/tó gbẹ.", "Bugharịa ihe na ndekọ a pụrụ iburu gaa n'ebe nchekwa dị elu/kpọrọ nkụ."],
  "Prepare livestock movement only to a location you already know is suitable.": ["Prepare livestock movement only go place wey you already know say safe and suitable.", "Shirya motsa dabbobi ne kawai zuwa wurin da ka riga ka san ya dace.", "Múra gbigbe ẹran-ọ̀sìn sí ibi tí o ti mọ̀ pé ó yẹ nìkan.", "Kwadebe ibugharị anụ ụlọ naanị gaa ebe ị maara na ọ dabara."],
  "Photograph current stock and equipment condition for evidence.": ["Take photo of current stock and equipment condition for evidence.", "Dauki hoton kayan ajiya da yanayin na'urori don shaida.", "Ya fọ́tò ipo ọjà àti ẹrọ báyìí fún ẹ̀rí.", "Were foto nke ngwaahịa na ọnọdụ akụrụngwa ugbu a maka ihe akaebe."],
  "Stop non-essential field work in exposed areas.": ["Stop work wey no urgent for exposed area.", "Dakatar da aikin da ba dole ba a wuraren da ke fuskantar hadari.", "Dá iṣẹ́ tí kò ṣe pàtàkì dúró ní agbègbè tó fara sí ewu.", "Kwụsị ọrụ ubi na-adịghị mkpa n'ebe ihe ize ndụ dị elu."],
  "Follow agricultural/emergency authority instructions.": ["Follow agriculture/emergency authority instruction.", "Bi umarnin hukumomin noma/gaggawa.", "Tẹ̀lé ìlànà aláṣẹ iṣẹ́-ogbin/pajawiri.", "Soro ntuziaka ụlọ ọrụ ọrụ ugbo/mberede."],
  "Submit a ground report if flooding reaches the farm so the event can be reviewed, not automatically treated as a model label.": ["If flood reach farm, send ground report make dem review am; no make system use am automatically as model label.", "Idan ambaliya ta isa gona, aika rahoton fili domin a duba lamarin; kada a dauke shi kai tsaye a matsayin label na model.", "Tí ìkún omi bá dé oko, fi ìròyìn ilẹ̀ ránṣẹ́ kí a lè ṣàyẹ̀wò rẹ; má ṣe jẹ́ kí model gba a gẹ́gẹ́ bí label láìsí àyẹ̀wò.", "Ọ bụrụ na idei mmiri eruo ubi, zipu akụkọ n'ebe ahụ ka a nyochaa ya; e kwesịghị iji ya ozugbo dị ka label model."],

  "A named person can activate the flood continuity plan when the trigger is reached.": ["One named person fit activate business flood plan when trigger reach.", "An nada mutum da zai kunna tsarin ci gaba da kasuwanci idan an kai matakin trigger.", "A ti yan ẹni kan tó lè ṣiṣẹ́ ètò ìtẹ̀síwájú iṣowo tí trigger bá dé.", "E nwere onye a kpọrọ aha nwere ike ịmalite atụmatụ azụmahịa mgbe trigger ruru."],
  "Staff communication and remote-work/closure instructions are prepared.": ["Staff message and remote-work/closure instruction don ready.", "An shirya sadarwar ma'aikata da umarnin aiki daga nesa/rufewa.", "A ti mú ìbánisọ̀rọ̀ òṣìṣẹ́ àti ìlànà iṣẹ́ láti ilé/títìpa ṣetán.", "A kwadebere nkwukọrịta ndị ọrụ na ntuziaka ọrụ site n'ụlọ/imechi."],
  "Critical stock, servers, documents and power equipment have a higher-ground plan.": ["Critical stock, server, document and power equipment get higher-ground plan.", "Muhimman kaya, server, takardu da na'urorin wuta suna da tsarin kaiwa sama.", "Ọjà pàtàkì, server, ìwé àti ohun èlò iná ní ètò gbigbe sókè.", "Ngwaahịa dị mkpa, server, akwụkwọ na akụrụngwa ọkụ nwere atụmatụ ibugharị elu."],
  "Suppliers/customers have a backup communication path for disruption.": ["Supplier/customer get backup way to communicate if disruption happen.", "Masu kaya/kwastomomi suna da wata hanyar sadarwa idan aka samu tangarda.", "Olùpèsè/oníbàárà ní ọ̀nà ìbánisọ̀rọ̀ àfikún tí ìdènà bá ṣẹlẹ̀.", "Ndị na-eweta ngwa/ndị ahịa nwere ụzọ nkwukọrịta ọzọ ma ihe kwụsị."],
  "Check whether an official advisory is active for the monitored location.": ["Check whether official advisory dey active for the place.", "Duba ko gargadin hukuma yana aiki a wurin da ake sa ido.", "Ṣàyẹ̀wò bóyá ìkìlọ̀ ìjọba wà nípò fún ibi náà.", "Lelee ma ịdọ aka ná ntị gọọmenti dị irè n'ebe a na-enyocha."],
  "Notify the person responsible for business continuity.": ["Tell the person wey dey responsible for business continuity.", "Sanar da mutumin da ke da alhakin ci gaba da kasuwanci.", "Fi tó ẹni tó ń bójú tó ìtẹ̀síwájú iṣowo létí.", "Gwa onye na-ahụ maka ịga n'ihu azụmahịa."],
  "Identify staff, inventory and critical systems in the most exposed area.": ["Know staff, inventory and critical system for the most exposed area.", "Gano ma'aikata, kaya da muhimman tsare-tsare a wurin da ya fi fuskantar hadari.", "Mọ òṣìṣẹ́, ọjà àti eto pàtàkì ní agbègbè tó fara sí ewu jù.", "Chọpụta ndị ọrụ, inventory na sistemụ dị mkpa n'ebe ihe ize ndụ kacha dị."],
  "Move high-value movable stock and documents above expected exposure.": ["Move valuable stock and document wey fit move go higher place.", "Daga kaya masu daraja da takardu zuwa sama da inda ake tsammanin ruwa zai kai.", "Gbe ọjà iyebíye àti ìwé tí a lè rú sókè ju ibi tí omi lè dé lọ.", "Bugharịa ngwaahịa bara uru na akwụkwọ a pụrụ iburu elu karịa ebe a tụrụ anya mmiri."],
  "Back up critical digital records and verify remote access.": ["Backup important digital record and check remote access.", "Yi ajiyar muhimman bayanan dijital kuma tabbatar da remote access.", "Ṣe àfẹ́yinti àkọsílẹ̀ díjítà pàtàkì kí o sì jẹ́rìí remote access.", "Mee backup ndekọ dijital dị mkpa ma nyochaa remote access."],
  "Prepare a closure/remote-work message before roads become unsafe.": ["Prepare closure/remote-work message before road unsafe.", "Shirya sakon rufewa/aiki daga nesa kafin hanyoyi su zama marasa aminci.", "Mú ifiranṣẹ́ títìpa/iṣẹ́ láti ilé ṣetán kí ọ̀nà tó di ewu.", "Kwadebe ozi imechi/ọrụ site n'ụlọ tupu ụzọ adị ize ndụ."],
  "Prioritise staff safety over protecting stock.": ["Staff safety come first before stock.", "Tsaron ma'aikata ya fi kare kaya muhimmanci.", "Fi ààbò òṣìṣẹ́ ṣáájú dídáàbò bo ọjà.", "Buru nchekwa ndị ọrụ ụzọ karịa ichekwa ngwaahịa."],
  "Suspend operations that require travel through affected areas.": ["Stop operation wey need travel through affected area.", "Dakatar da ayyukan da ke bukatar tafiya ta wuraren da abin ya shafa.", "Dá iṣẹ́ tí ó nílò irin-ajo kọjá agbègbè tí ewu kan dúró.", "Kwụsị ọrụ chọrọ njem gafee ebe ihe metụtara."],
  "Record decisions and losses in the evidence workflow for later audit/insurance discussions.": ["Record decision and loss for evidence, audit and insurance later.", "Rubuta hukunci da asara a tsarin shaida don bincike/insurance daga baya.", "Kọ ìpinnu àti adánù sínú ẹ̀rí fún audit/insurance nígb later.", "Dekọọ mkpebi na mfu n'usoro ihe akaebe maka audit/insurance n'ọdịnihu."],

  "Duty operator and escalation contacts are assigned for the current shift.": ["Duty operator and escalation contact don assign for this shift.", "An sanya duty operator da lambobin daukaka mataki na wannan shift.", "A ti yan duty operator àti kọ́ntáàkì escalation fún shift yìí.", "E kenyere duty operator na kọntaktị escalation maka shift a."],
  "Official advisory source/freshness can be verified before actioning it.": ["Official advisory source and freshness fit verify before action.", "Ana iya tabbatar da tushen gargadin hukuma da sabuntawarsa kafin a yi aiki.", "A lè jẹ́rìí orísun àti ìmúdójúìwọ̀n ìkìlọ̀ ìjọba kí a tó gbé ìgbésẹ̀.", "A pụrụ nyochaa isi mmalite na freshness nke ịdọ aka ná ntị gọọmenti tupu ime ihe."],
  "Priority communities/assets and communication channels are pre-identified.": ["Priority community/assets and communication channel don identify before time.", "An riga an gano al'ummomi/kadarori masu fifiko da hanyoyin sadarwa.", "A ti mọ àwùjọ/ohun-ini tó ní àkọ́kọ́ àti ikanni ìbánisọ̀rọ̀ ṣáájú.", "A matala obodo/akụ ndị kacha mkpa na ụzọ nkwukọrịta tupu oge eruo."],
  "Every acknowledge/escalate/resolve action will be captured in the evidence ledger.": ["Every acknowledge/escalate/resolve action go enter evidence ledger.", "Za a rubuta kowane acknowledge/escalate/resolve a cikin evidence ledger.", "Gbogbo acknowledge/escalate/resolve ni a ó kọ sínú evidence ledger.", "A ga-edekọ acknowledge/escalate/resolve ọ bụla n'ime evidence ledger."],
  "Verify whether a fresh canonical official advisory is present.": ["Verify whether fresh official advisory dey present.", "Tabbatar ko akwai sabon canonical gargadin hukuma.", "Jẹ́rìí bóyá ìkìlọ̀ ìjọba tuntun canonical wà.", "Nyochaa ma canonical ịdọ aka ná ntị gọọmenti ọhụrụ dị."],
  "Review source health and identify missing/stale feeds instead of treating them as safe.": ["Check source health and find missing/stale feed; no treat missing data as safe.", "Duba lafiyar source kuma gano feed da ya bace/tsufa; kada a dauke rashin data a matsayin lafiya.", "Ṣàyẹ̀wò source health, mọ feed tó sọnù/tó ti pẹ́; má ka àìsí data sí ààbò.", "Lelee source health ma chọpụta feed furu efu/ochie; elela data efu anya dị ka nchekwa."],
  "Open the Agency Command Queue for any actionable advisory.": ["Open Agency Command Queue for any advisory wey need action.", "Bude Agency Command Queue ga duk gargadin da ke bukatar aiki.", "Ṣí Agency Command Queue fún ìkìlọ̀ tó nílò ìgbésẹ̀.", "Mepee Agency Command Queue maka ịdọ aka ná ntị chọrọ ihe omume."],
  "Acknowledge and assign ownership of active cases.": ["Acknowledge active case and assign owner.", "Acknowledge shari'o'in da ke aiki kuma sanya mai alhaki.", "Acknowledge case tó ń ṣiṣẹ́ kí o sì yan ẹni tó ní ojúṣe.", "Acknowledge ikpe ndị dị irè ma kenye onye nwe ọrụ."],
  "Use verified field reports as supporting evidence; pending reports are not official truth.": ["Use verified field report as support; pending report no be official truth.", "Yi amfani da verified field report a matsayin shaida; pending report ba gaskiyar hukuma ba ne.", "Lo verified field report gẹ́gẹ́ bí ẹ̀rí; pending report kì í ṣe òtítọ́ ìjọba.", "Jiri verified field report dị ka ihe akaebe; pending report abụghị eziokwu gọọmenti."],
  "Choose delivery channels and target areas without rewriting the authority's source message.": ["Choose delivery channel and target area without changing authority source message.", "Zabi hanyoyin isarwa da wuraren da za a kai ba tare da canza sakon hukumar ba.", "Yan ikanni ìfiránṣẹ́ àti agbègbè àfojúsùn láì tún ọ̀rọ̀ aláṣẹ kọ.", "Họrọ ụzọ izipu na ebe ebumnuche na-enweghị idegharịa ozi isi ụlọ ọrụ."],
  "Record escalation/resolution in the append-only evidence flow.": ["Record escalation/resolution for append-only evidence flow.", "Rubuta escalation/resolution a cikin append-only evidence flow.", "Kọ escalation/resolution sínú append-only evidence flow.", "Dekọọ escalation/resolution n'ime append-only evidence flow."],
  "Review failed deliveries and unverified reports.": ["Review failed delivery and unverified report.", "Duba isarwar da ta gaza da rahotannin da ba a tabbatar ba.", "Ṣàyẹ̀wò ìfiránṣẹ́ tó kùnà àti ìròyìn tí a kò tíì jẹ́rìí.", "Nyochaa izipu dara ada na akụkọ a na-akwadoghị."],
  "Preserve misses and false alarms for post-event learning instead of deleting them.": ["Keep miss and false alarm for learning after event; no delete am.", "Ajiye misses da false alarms don koyo bayan lamarin maimakon gogewa.", "Pa misses àti false alarms mọ́ fún ẹ̀kọ́ lẹ́yìn iṣẹlẹ̀; má parẹ́ wọn.", "Chekwaa misses na false alarms maka mmụta mgbe ihe gasịrị kama ihichapụ ha."],

  "This page contains general flood-safety actions only. It deliberately avoids live risk numbers, invented routes and unverified shelter locations so the cached version cannot pretend stale information is current.": ["This page get general flood-safety action only. E no show stale live number, invented road or unverified shelter so cached copy no go pretend say old info na current.", "Wannan shafi yana dauke da matakan tsaron ambaliya na gaba daya kawai. Ba ya nuna tsohon live risk, kirkirar hanya ko wurin mafaka da ba a tabbatar ba domin cached copy kada ya nuna tsohon bayani a matsayin sabo.", "Ojú-ewé yìí ní ìgbésẹ̀ ààbò ìkún omi gbogbogbo nìkan. Kò fi live risk atijọ́, ọ̀nà tí a dá sílẹ̀ tàbí ibi ààbò tí a kò jẹ́rìí hàn, kí cached copy má ṣe fi ògbólógbòó data hàn bí tuntun.", "Peeji a nwere naanị usoro nchekwa idei mmiri zuru oke. Ọ naghị egosi live risk ochie, ụzọ e mepụtara ma ọ bụ shelter a na-akwadoghị ka cached copy ghara ime ka ozi ochie bụrụ nke ọhụrụ."],
  "If an authority tells you to move, evacuate or avoid an area, follow that instruction. A low app score must never override it.": ["If authority tell you move, evacuate or avoid area, follow am. Low app score no fit cancel am.", "Idan hukuma ta ce ka matsa, fice ko guji wuri, bi umarnin. Karamin app score ba zai soke shi ba.", "Tí aláṣẹ bá ní kí o kúrò, evacuate tàbí yàgò fún agbègbè, tẹ̀lé e. Iye app kéré kò gbọ́dọ̀ fagilé rẹ.", "Ọ bụrụ na ọchịchị agwa gị ka ị kwaga, pụọ ma ọ bụ zere ebe, soro ntuziaka. App score dị ala enweghị ike ịkagbu ya."],
  "Do not walk, drive or send children through flooded roads, drains, channels or fast-moving water.": ["No waka, drive or send children through flooded road, drain, channel or fast water.", "Kada ka yi tafiya, tuki ko aika yara ta tituna, magudana ko ruwa mai karfi da ambaliya ta rufe.", "Má rìn, wakọ̀ tàbí rán ọmọ kọjá ọ̀nà, kòtò, ikanni tàbí omi tó ń sáré tí ìkún bo.", "Agala ije, akwọla ụgbọala ma ọ bụ zipu ụmụaka gafee ụzọ, ọwa mmiri ma ọ bụ mmiri na-agba ọsọ jupụtara."],
  "Charge phones and power banks. Write down important contacts so they are available even if your phone cannot load cloud data.": ["Charge phone/power bank. Write important contact down so e dey even if cloud no load.", "Caji waya/power bank. Rubuta muhimman lambobi domin su kasance koda waya ba ta iya loda cloud data ba.", "Gba fóònù/power bank lágbára. Kọ kọ́ntáàkì pàtàkì sílẹ̀ kí wọ́n wà bí cloud data kò bá load.", "Chajie ekwentị/power bank. Dee kọntaktị dị mkpa ka ha dị ọbụna ma cloud data anaghị load."],
  "Keep medicines, identity documents and other essential records together and easy to carry.": ["Keep medicine, ID document and important record together where you fit carry quick.", "Ajiye magunguna, takardun shaida da muhimman bayanai tare kuma cikin saukin dauka.", "Pa oogun, ìwé ìdánimọ̀ àti àkọsílẹ̀ pàtàkì pọ̀ níbi tí a lè gbé rọrùn.", "Debe ọgwụ, akwụkwọ njirimara na ndekọ dị mkpa ọnụ n'ebe a pụrụ iburu mfe."],
  "If it is safe and there is time, move important portable items and electrical equipment away from low floors and exposed areas.": ["If e safe and time dey, move important portable things and electrical equipment from low floor/exposed area.", "Idan lafiya ne kuma akwai lokaci, motsa muhimman kaya da na'urorin lantarki daga kasa da wuraren da ke fuskantar hadari.", "Tí ó bá láàbò àti pé àkókò wà, gbe ohun pàtàkì àti ẹrọ iná kúrò ní ilẹ̀ kékeré àti ibi tó fara sí ewu.", "Ọ bụrụ na ọ dị nchebe ma oge dị, bugharịa ihe dị mkpa na ngwa eletrik pụọ n'ala dị ala na ebe ekpughere."],
  "Help children, older people, people with disabilities and anyone who needs extra assistance before protecting property.": ["Help children, older people, people with disability and anybody wey need extra help before property.", "Taimaka wa yara, tsofaffi, masu nakasa da duk wanda ke bukatar karin taimako kafin kare dukiya.", "Ran ọmọ, àgbàlagbà, ẹni tó ní àìlera àti ẹni tó nílò ìrànlọ́wọ́ lọ́wọ́ kí o tó dáàbò bo ohun-ini.", "Nyere ụmụaka, ndị okenye, ndị nwere nkwarụ na onye chọrọ enyemaka ọzọ tupu ichekwa ihe onwunwe."],
  "Emergency and family contacts written on paper": ["Emergency and family contact written for paper", "Lambobin gaggawa da iyali an rubuta a takarda", "Kọ́ntáàkì pajawiri àti ẹbí tí a kọ sí bébà", "Kọntaktị mberede na ezinụlọ e dere n'akwụkwọ"],
  "Medicines and important documents together": ["Medicine and important document together", "Magunguna da muhimman takardu tare", "Oogun àti ìwé pàtàkì papọ̀", "Ọgwụ na akwụkwọ dị mkpa ọnụ"],
  "Charged phone and power bank": ["Charged phone and power bank", "Waya da power bank da aka caji", "Fóònù àti power bank tó ti gba agbára", "Ekwentị na power bank a chajịrị"],
  "Torch/light source and essential supplies": ["Torch/light and essential supplies", "Tocila/haske da muhimman kayayyaki", "Tọ́ọ̀ṣì/ìmọ́lẹ̀ àti ohun èlò pàtàkì", "Torch/ìhè na ihe dị mkpa"],
  "A known authority-approved relocation destination if one has been given": ["Authority-approved place wey you already know if dem don give one", "Wurin matsawa da hukuma ta amince da shi idan an bayar", "Ibi ìṣípo tí aláṣẹ fọwọ́ sí tí a bá ti sọ ọ", "Ebe ịkwaga nke ọchịchị kwadoro ma ọ bụrụ na e nyere ya"],
  "Photos/inventory of important assets where useful": ["Photo/inventory of important asset where useful", "Hotuna/jadawalin muhimman kadarori idan ya dace", "Fọ́tò/àkọsílẹ̀ ohun-ini pàtàkì bí ó bá wúlò", "Foto/ndepụta akụ dị mkpa ebe o bara uru"],
  "Live check needs a connection": ["Live check need network", "Live check na bukatar network", "Live check nílò ayélujára", "Live check chọrọ network"],
  "Do not use a cached page as a current warning.": ["No use cached page as current warning.", "Kada ka yi amfani da cached page a matsayin gargadi na yanzu.", "Má lo cached page gẹ́gẹ́ bí ìkìlọ̀ lọwọlọwọ.", "Ejila cached page dị ka ịdọ aka ná ntị ugbu a."],
  "When you regain connectivity, refresh live conditions and check current official instructions. If you can already see dangerous flooding, act on what is physically happening around you rather than waiting for an app update.": ["When network come back, refresh live condition and check current official instruction. If you already see dangerous flood, act on wetin dey happen around you instead of waiting for app update.", "Idan network ya dawo, sabunta live condition kuma duba umarnin hukuma na yanzu. Idan ka riga ka ga ambaliya mai hatsari, yi aiki da abin da ke faruwa maimakon jiran app update.", "Tí ayélujára bá padà, refresh live condition kí o sì ṣàyẹ̀wò ìlànà ìjọba lọwọlọwọ. Tí o bá ti rí ìkún omi tó lewu, ṣe ohun tó yẹ gẹ́gẹ́ bí ohun tó ń ṣẹlẹ̀ káàkiri rẹ, má dúró de app update.", "Mgbe network lọghachiri, refresh live condition ma lelee ntuziaka gọọmenti ugbu a. Ọ bụrụ na ị hụla idei mmiri dị ize ndụ, mee ihe dabere n'ihe na-eme gburugburu gị kama ichere app update."],
  "Low-bandwidth design: no map, no chart and no live API are required to read this emergency pack once cached.": ["Low-bandwidth design: once e cache, you no need map, chart or live API to read this emergency pack.", "Tsarin low-bandwidth: idan an cache shi, ba a bukatar map, chart ko live API don karanta emergency pack.", "Low-bandwidth design: tí a bá ti cache rẹ, o kò nílò map, chart tàbí live API láti ka emergency pack yìí.", "Low-bandwidth design: ozugbo e cached ya, map, chart ma ọ bụ live API adịghị mkpa iji gụọ emergency pack a."],

  "Practice scenario: a HIGH flood-risk signal appears for your neighbourhood and heavy rain is continuing. No official evacuation order is simulated.": ["Practice: HIGH flood-risk signal show for your area and heavy rain still dey fall. No official evacuation order dey simulated.", "Atisaye: HIGH flood-risk signal ya bayyana a yankinku kuma ruwan sama mai yawa yana ci gaba. Ba a kwaikwayi umarnin ficewa na hukuma ba.", "Ìdánilẹ́kọ̀ọ́: HIGH flood-risk signal farahàn ní agbègbè rẹ, òjò líle sì ń tẹ̀síwájú. Kò sí official evacuation order nínú àdánwò yìí.", "Ọzụzụ: HIGH flood-risk signal pụtara n'ógbè gị, nnukwu mmiri ozuzo ka na-aga. Enweghị official evacuation order a na-eme simulation."],
  "Practice scenario: sustained rainfall and a HIGH flood-risk signal threaten farm access over the next day. This drill does not claim a real flood is coming.": ["Practice: steady rain and HIGH flood-risk signal fit affect farm access next day. This drill no talk say real flood dey come.", "Atisaye: ruwan sama mai dorewa da HIGH flood-risk signal na iya hana shiga gona gobe. Wannan atisayen ba ya cewa ambaliya ta gaske na zuwa.", "Ìdánilẹ́kọ̀ọ́: òjò tó ń tẹ̀síwájú àti HIGH flood-risk signal lè kan ọ̀nà sí oko lọ́la. Àdánwò yìí kò sọ pé ìkún omi gidi ń bọ̀.", "Ọzụzụ: mmiri ozuzo na-aga n'ihu na HIGH flood-risk signal nwere ike imetụta ụzọ ubi n'ụbọchị na-abịa. Drill a anaghị ekwu na idei mmiri n'ezie na-abịa."],
  "Practice scenario: a HIGH flood-risk signal affects a monitored business location during operating hours. No real closure order is being issued.": ["Practice: HIGH flood-risk signal affect business place during work time. No real closure order dey issued.", "Atisaye: HIGH flood-risk signal ya shafi wurin kasuwanci lokacin aiki. Ba a bayar da umarnin rufewa na gaske ba.", "Ìdánilẹ́kọ̀ọ́: HIGH flood-risk signal kan ibi iṣowo ní àkókò iṣẹ́. Kò sí real closure order.", "Ọzụzụ: HIGH flood-risk signal metụtara ebe azụmahịa n'oge ọrụ. Enweghị real closure order a na-enye."],
  "Practice scenario: a fresh authenticated official advisory enters the command queue. This is a simulation and does not represent a real authority warning.": ["Practice: fresh authenticated official advisory enter command queue. Na simulation; e no be real authority warning.", "Atisaye: sabon authenticated official advisory ya shiga command queue. Wannan simulation ne, ba gargadin hukuma na gaske ba.", "Ìdánilẹ́kọ̀ọ́: authenticated official advisory tuntun wọ command queue. Àdánwò ni; kì í ṣe ìkìlọ̀ aláṣẹ gidi.", "Ọzụzụ: authenticated official advisory ọhụrụ batara command queue. Nke a bụ simulation, ọ bụghị ịdọ aka ná ntị gọọmenti n'ezie."],
  "Tell everyone in the household that this is a practice drill.": ["Tell everybody for house say na practice drill.", "Faɗa wa kowa a gida cewa wannan atisaye ne.", "Sọ fún gbogbo ènìyàn nílé pé ìdánilẹ́kọ̀ọ́ ni.", "Gwa onye ọ bụla n'ụlọ na nke a bụ ọzụzụ."],
  "Locate medicines, identity documents and the grab-ready essentials you would take.": ["Find medicine, ID document and important things wey you go carry.", "Nemo magunguna, takardun shaida da muhimman kayan da za ka dauka.", "Wa oogun, ìwé ìdánimọ̀ àti ohun pàtàkì tí iwọ yóò gbé.", "Chọta ọgwụ, akwụkwọ njirimara na ihe dị mkpa ị ga-eburu."],
  "Confirm who would assist children, older people or anyone needing extra help.": ["Confirm who go help children, older people or anybody wey need extra help.", "Tabbatar wanda zai taimaka wa yara, tsofaffi ko duk mai bukatar karin taimako.", "Jẹ́rìí ẹni tó máa ran ọmọ, àgbàlagbà tàbí ẹni tó nílò ìrànlọ́wọ́ lọ́wọ́.", "Kwenye onye ga-enyere ụmụaka, ndị okenye ma ọ bụ onye chọrọ enyemaka ọzọ."],
  "Check that emergency contacts are available offline and phones/power banks can be charged.": ["Check emergency contact dey offline and phone/power bank fit charge.", "Duba cewa lambobin gaggawa suna offline kuma ana iya caji waya/power bank.", "Ṣàyẹ̀wò pé kọ́ntáàkì pajawiri wà offline, fóònù/power bank sì lè gba agbára.", "Lelee na kọntaktị mberede dị offline ma ekwentị/power bank nwere ike ịchaji."],
  "Say out loud what would make you stop the drill and follow a real authority instruction instead.": ["Talk out loud wetin go make you stop drill and follow real authority instruction.", "Faɗi abin da zai sa ka dakatar da atisaye ka bi umarnin hukuma na gaske.", "Sọ ohun tí yóò jẹ́ kí o dá àdánwò dúró kí o sì tẹ̀lé ìlànà aláṣẹ gidi.", "Kwuo ihe ga-eme ka ị kwụsị drill ma soro ntuziaka gọọmenti n'ezie."],
  "This mode never creates or sends a real warning. It does not change the live model score, contact emergency services, write an operational evidence event or claim that a flood is occurring. Stop the drill immediately if a real official warning or dangerous visible condition appears.": ["This mode no dey create or send real warning. E no change live model score, contact emergency service, write operational evidence or claim say flood dey happen. Stop drill immediately if real official warning or dangerous condition show.", "Wannan yanayin ba ya kirkiro ko aika gargadi na gaske. Ba ya canza live model score, tuntubar emergency service, rubuta operational evidence ko cewa ambaliya na faruwa. Dakatar da atisaye nan take idan gargadin hukuma na gaske ko hadari ya bayyana.", "Ipo yìí kò ṣẹ̀dá tàbí fi ìkìlọ̀ gidi ránṣẹ́. Kò yí live model score padà, kò kan emergency service, kò kọ operational evidence, kò sì sọ pé ìkún omi ń ṣẹlẹ̀. Dá àdánwò dúró lẹ́sẹ̀kẹsẹ̀ tí ìkìlọ̀ ìjọba gidi tàbí ewu tí o rí bá farahàn.", "Ụdị a anaghị emepụta ma ọ bụ zipu ịdọ aka ná ntị n'ezie. Ọ naghị agbanwe live model score, kpọtụrụ emergency service, dee operational evidence ma ọ bụ kwuo na idei mmiri na-eme. Kwụsị drill ozugbo ma real official warning ma ọ bụ ọnọdụ dị ize ndụ pụta."],
  "Practice checklist": ["Practice checklist", "Jerin atisaye", "Àtòjọ ìdánilẹ́kọ̀ọ́", "Ndepụta ọzụzụ"],
  "drill progress": ["drill progress", "ci gaban atisaye", "ìlọsíwájú àdánwò", "ọganihu drill"],
  "Reset drill": ["Reset drill", "Sake fara atisaye", "Tún àdánwò bẹ̀rẹ̀", "Malite drill ọzọ"],
  "Improve my readiness": ["Improve my readiness", "Inganta shirina", "Mú ìmúrasílẹ̀ mi dára", "Melite nkwadebe m"],
  "Practice complete": ["Practice complete", "An kammala atisaye", "Ìdánilẹ́kọ̀ọ́ parí", "Ọzụzụ agwụla"],
  "Use the debrief to find weaknesses before a real event.": ["Use debrief find weak point before real event.", "Yi amfani da debrief don gano rauni kafin lamarin gaske.", "Lo debrief láti rí àìlera kí iṣẹlẹ̀ gidi tó ṣẹlẹ̀.", "Jiri debrief chọpụta adịghị ike tupu ihe n'ezie emee."],
  "Drill completion is local practice information only and is not recorded as emergency-response evidence.": ["Drill completion na local practice info only; e no enter emergency-response evidence.", "Kammala drill bayanin atisaye na local ne kawai; ba a rubuta shi a matsayin emergency-response evidence ba.", "Ìparí drill jẹ́ local practice info nìkan; a kò kọ ọ́ gẹ́gẹ́ bí emergency-response evidence.", "Mmecha drill bụ local practice info naanị; a naghị edekọ ya dị ka emergency-response evidence."],
};

const locales: Exclude<AppLocale, "en">[] = ["pcm", "ha", "yo", "ig"];
const reverse = new Map<string, string>();
for (const [english, row] of Object.entries(ROWS)) {
  reverse.set(english, english);
  row.forEach((value) => reverse.set(value, english));
}

export function translateActionOSDetailExact(value: string, locale: AppLocale) {
  const english = reverse.get(value);
  if (!english || locale === "en") return english || value;
  const row = ROWS[english];
  const index = locales.indexOf(locale as Exclude<AppLocale, "en">);
  return index >= 0 ? row[index] : value;
}
